### ISSUE TITLE
特定の長さ以上の文字列で、ダブルクォートが escape されない

### ISSUE THREAD

**Issue by skawaji** [k0kubun/hescape-ruby#2]
こんにちは。

手元での Benchmark の結果がかなり良いので使わせていただこうと思ったのですが、特定の長さ以上の場合か、あるいはそれ以外の何らかの条件で、escape がされないことがあるようです。

以下、なるべく最小にした再現方法です。

```ruby
RUBY_VERSION #=> '2.5.3'

require 'cgi'
require 'hescape'

s = '{ "lat": 35.000000, "l'
CGI.escapeHTML(s)                            #=> "{ &quot;lat&quot;: 35.000000, &quot;l"
Hescape.escape_html(s)                       #=> "{ &quot;lat\": 35.000000, &quot;l"
CGI.escapeHTML(s) == Hescape.escape_html(s)  #=> false
```

**Comment by k0kubun** [comment]
ご検討と丁寧なご報告ありがとうございます。現在デバッグしておりますので、少々お待ちください。

**Comment by k0kubun** [comment]
バグ修正と、ちょっとした最適化を入れたバージョン v0.1.1をリリースしました。ご確認ください。
この度はこちらのバグを報告していただきありがとうございました。:bow:

**Comment by k0kubun** [comment]
というか、元々のコードでは既に修正していた https://github.com/k0kubun/hescape/commit/356c8878f6bb4acd5a1d2f9711b3450afce9d0e3 のを単にこちらにバックポートしていなかったという話なのを今更思い出しました…
いずれにせよ、該当の問題はhescape.gemでも修正されたかと思います。

**Comment by skawaji** [comment]
早速のご対応、ありがとうございました。こちらでは、全て意図通りの動作になりました。

報告時に gemのバージョンも付記すれば良かったです。
まもなくの Ruby の JIT対応、使う時を楽しみにしています。
